Fix/logging
joaxcar/iv1201-group-5 pull request #36
Opened 2021-02-23 11:08 UTC by nedvin

Logging proof of concept.

Error logs are sent to Sentry as long as the environment variable SENTRY_DSN is set, otherwise not. This solves the problem of not sending lots of development logs to the cloud.

When running the application locally, logs at level INFO or higher (WARN, ERROR) are printed to STDOUT. If we want to set a lower level we can use a little script (run.sh) that is provided with this PR. Instructions on how to run the script is provided inside it.

closes #31

2021-02-23 15:30 UTC, RW90 requested changes
One minor change requested, I tried out my suggestion and it worked decently.

2021-02-23 15:30 UTC, RW90 commented on backend/src/main/java/se/kth/iv1201/recruitmentapplicationgroup5/controller/ApiExceptionHandler.java
> +		log.debug(e.getStackTrace().toString());
This only prints the pointer to the array of stacks. I recommend changing this line to: 
log.debug(Arrays.toString(e.getStackTrace()).replaceAll(",", "\n"));

For other alternatives, solutions see https://stackoverflow.com/questions/1149703/how-can-i-convert-a-stack-trace-to-a-string

2021-02-23 21:24 UTC, RW90 approved these changes

2021-02-25 10:29 UTC, joaxcar approved these changes

2021-02-25 12:55 UTC, merged